### Get health
GET http://0.0.0.0:5000/health


### Get weather data for a specific location
GET http://0.0.0.0:5000/free/Campinas


### Create account
POST http://0.0.0.0:5000/account
Content-Type: application/json

{
  "nome": "marcelo",
  "email": "marcelo@email.com"
}


### Get account
GET http://0.0.0.0:5000/account/user/marcelo@email.com


### Get weather data for a specific location with account
GET http://0.0.0.0:5000/weather/Campinas/985f24df-1f5d-4614-9284-2e9646648804


### Get History
GET http://0.0.0.0:5000/history/985f24df-1f5d-4614-9284-2e9646648804

