version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    dns: 
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - raizen_default
networks:
  raizen_default:

